### ISSUE TITLE
[Q] docker-compose - what are apache & php containers for?

### ISSUE THREAD

**Issue by laur89** [johndatserakis/koa-vue-notes-api#11]
Hi, first off thanks for the amazing example program.

My question is pretty much as in the title - this is our backend service, what are those services declared in docker-compose for?

I'm especially curious about why php image is included.

**Comment by johndatserakis** [comment]
Hey there, thanks for checking out the repo.

Sorry for the confusion, but those other services don't really have anything to do with this program. They are just part of a reliable Docker environment I use as a base. A while back I used PHP for some of my backends, so that's why`php` and `apache` are in the`docker-compose.yml` file services section.

Really, the only services you need in the `docker-compose.yml` file are the `mysql` and `redis` entries.

Sorry for the confusion!

**Comment by laur89** [comment]
Cool, that clears it.
Would you accept a PR removing those two?

**Comment by johndatserakis** [comment]
Hey @laur89 - sure, but you don't have to go out of your way to do that. If you have the time though, yea that would be great. In addition to removing the `php` and `apache` blocks in the `./docker-compose.yml` file, we'll also need to remove the `./docker/apache`, `./docker/php`, and`./docker/nginx` folders. Let me know if you can get to it, if not that's fine - I'll try to get to it later.

Thank you!
