### ISSUE TITLE
Trouble running on windows

### ISSUE THREAD

**Issue by Trellian** [johndatserakis/koa-vue-notes-api#2]
Hi John, 

I'm having some trouble running under Windows (10).

Initially, I had trouble getting NODE_ENV set, but I fixed that in package.json by adding 'set' in front of the NODE_ENV directive. Interestingly, i tried using 'cross-env', but it didn't work. Weird.

Now I'm trying to do 'npm run watch', but getting the following:

> koa-vue-notes-api@1.2.6 watch C:\xampp\htdocs\koa-notes-api
> set NODE_ENV=development & nodemon app.js --exec

[nodemon] 1.12.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
```
C:\xampp\htdocs\koa-notes-api\src\index.js:3
import Koa from 'koa'
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    ....
    at Object.<anonymous> (C:\xampp\htdocs\koa-notes-api\app.js:12:13)

```
I'm running node 8.x, so it shouldn't be an ES2015 thing surely?  I know this is not really your problem, but do you perhaps have any ideas I can try?

**Comment by johndatserakis** [comment]
No problem. First, I would say to make sure you have the following in your package.json:

```
"babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": [
              "last 2 versions",
              "safari >= 7"
            ]
          }
        }
      ]
    ]
  },
```

Perhaps you had deleted that by mistake. If that still doesn't work - then create a .babelrc file in your root directory, delete the above from your package.json, and add this to your newly created .babelrc file:

```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 7"
          ]
        }
      }
    ]
  ]
}
```

The reason I'm having you try this is because I figure there may be a chance Windows has an issue reading the babel config from the package.json.

Now, as to why all this is needed - you actually still need babel to use import in node - even in the newer versions. No biggie - just use the [babel-preset-env](https://github.com/babel/babel-preset-env) package like I do in this project and it handles it for you. Then, when you build the project and run the project in production with `NODE_ENV=production`, the `app.js` file with know to use the files in the generated `build` folder in the project with the code that's already been transpilled.

**Comment by Trellian** [comment]
Thanks for coming back to me! 

I hadn't deleted the "babel": section in packages.json, but I tried what you suggested regardless. It's still not working.

I haven't made any other changes since cloning the project. So 'package.json is the original 

I also tried an npm update, after these changes, and strangely enough it produced the following, which I wasn't expecting:

```
+ fs-extra@4.0.2
+ npm@5.5.1
+ log4js@2.3.4
+ prettier@1.7.4
+ pm2@2.7.1
+ nodemon@1.12.1
added 169 packages, removed 5 packages and updated 46 packages

```
But still no luck. I will try a few more things and get back to you.

**Comment by johndatserakis** [comment]
Hmm, at that point I would delete the entire `node_modules` folder and `npm install` again just to be safe. Those updates should be fine. I'll be continuing to research as well.

**Comment by Trellian** [comment]
Good advice, let me try it

**Comment by Trellian** [comment]
@johndatserakis , 

Ok, I tried that, still no joy. Perhaps I can post my configs for you to have a look at?

package.json(.txt):

[package.json.txt](https://github.com/johndatserakis/koa-vue-notes-api/files/1362262/package.json.txt)

.babelrc

`{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 7"
          ]
        }
      }
    ]
  ]
}
`

npm-packages:

[npm-packages.txt](https://github.com/johndatserakis/koa-vue-notes-api/files/1362257/npm-packages.txt)

and, last, the output:

![image](https://user-images.githubusercontent.com/1085100/31272738-4b3cf0ee-aa8c-11e7-9ff8-d7eeacc496a0.png)

**Comment by Trellian** [comment]
Perhaps I should just put it up in a linux VM ;D

**Comment by johndatserakis** [comment]
Hmm, strange. One thing I would do is `npm uninstall cross-env` - as it could be fighting with the `babel-present-env` and thus not letting the `babel-preset-env` do its job.

I will say that I get the same error if I remove the babel-json information from my project - so the issue is definitely due to babel not being able to do its thing properly.

**Comment by Trellian** [comment]
Ok, I spun it up in a linux VM, and while that problem has resolved itself... another has surfaced. I'm pretty sure this one isn't your problem, but I'd appreciate it if you could comment.  The error as follows:

![screenshot from 2017-10-06 12-00-03](https://user-images.githubusercontent.com/1085100/31287131-90b946ca-aac0-11e7-840f-cc29df798db0.png)

I have no idea about how to tackle this one :o

**Comment by johndatserakis** [comment]
Make sure you have the node version in your vm updated to a latest version. I use [nvm](https://github.com/creationix/nvm) in virtual machines if need be.

**Comment by johndatserakis** [comment]
How's it going with this issue?

**Comment by Trellian** [comment]
Hi John, I never got it sorted out under windows, but it's working great in Ubuntu (which is where it's going to live eventually anyway :) ).

A couple of things that you might want to consider adding to the docs/code (for streamlining the setup):

1) knex apparently needs to be installed globally in order to be able to run migrations:
$npm install -g knex

2) The database names in knexfile.js eg (database: process.env.DB_DATABASE + '_testing',
) doesn't have the '_dev' suffix for the development db (so it's the same as the production db name)

3) The users seed doesn't setup the default demousername user

Thanks for an excellent example on Vue +  koa + jwt auth !

**Comment by johndatserakis** [comment]
No problem, thanks for the suggestions. I'll be updating the readme soon. I didn't intend to have the demousername/demopassword in the seeding - but that may help users in the future. And as far as the `_dev` suffix - that's ok (for me) if they share the same name - as they'll be using totally different connections - but perhaps that could help prevent migrating overwrites done by accident.

Thank you!
