### ISSUE TITLE
Token in User

### ISSUE THREAD

**Issue by unteem** [johndatserakis/koa-vue-notes-api#3]
Hi. First thanks for sharing your work.Its been a great inspiration for learning koa and vue. 

I don't really get what this token in the user model/controller is doing? Maybe I missed something but it seems that it is genreated but not used.
https://github.com/johndatserakis/koa-vue-notes-api/blob/5e5121dafb05dbf981163da36c7a5439759da465/src/controllers/UserActionController.js#L94-L95

**Comment by johndatserakis** [comment]
Good question - I generate a token there to give the user a unique value that's *separate* from the autogenerated incrementing `id`.

The reason I do this is because sometimes you may want to identify a user, or any object from the database, in a way that does not give away any database details. For instance, if you refer to a user in a public url and use their id, you are publicly displaying how many users your program has.

Now, this isn't actually the biggest deal, but what I started doing a while back to mitigate any negative effects was to create a unique token alongside the newly created user that could be used to identify the user just like an `id`, but not give away any further details. In this program I don't think I used it further, but if there was a public route I may have elected to use it there.

**Comment by johndatserakis** [comment]
Closing for now
