### ISSUE TITLE
how to add front-end framework in this repo, like vue. Thanks.

### ISSUE THREAD

**Issue by LennieLT** [johndatserakis/koa-vue-notes-api#7]

**Comment by johndatserakis** [comment]
Hello, 

You're in luck because this project has a partner - [koa-vue-notes-web](https://github.com/johndatserakis/koa-vue-notes-web) that is specifically made to work with this repo.

To use them together, just get this one booted up, then start the frontend version - you should be good to go.

Let me know if you can't get it going. Thanks!

**Comment by johndatserakis** [comment]
Closing for now - let me know if I can answer anything else - thanks.
